name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate repository as an integration
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Home Assistant integration metadata
        uses: home-assistant/actions/hassfest@master
